#! /bin/sh
# kcminputrc Mouse cursorTheme 'Oxygen_White'
kcminputrc_mouse_cursortheme=BlackStyle
# kcminputrc Mouse cursorSize ''
kcminputrc_mouse_cursorsize=0
# ksplashrc KSplash Theme Default
ksplashrc_ksplash_theme=黑之靈夢
# ksplashrc KSplash Engine KSplashX
ksplashrc_ksplash_engine=KSplashX
# krandrrc Display ApplyOnStartup false
krandrrc_display_applyonstartup=true
# krandrrc Display StartupCommands ''
krandrrc_display_startupcommands='xrandr --output DVI-I-0 --pos 0x0 --mode 1440x900 --refresh 59.8874
xrandr --output DVI-D-0 --pos 1440x0 --mode 1920x1080 --refresh 60
xrandr --output DVI-D-0 --primary'
# krandrrc [Screen0]
# krandrrc [Screen1]
# krandrrc [Screen2]
# krandrrc [Screen3]
# kcmfonts General forceFontDPI 0
kcmfonts_general_forcefontdpi=0
# kdeglobals Locale Language '' # trigger requesting languages from KLocale
kdeglobals_locale_language=''
klocale_languages=en_US
